# master-pipeline.yml
name: MasterPipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none  # Manual trigger only

resources:
  pipelines:
  # Pipeline 1 - AlloyDB Deployment
  - pipeline: alloydb-pipeline
    source: Pipeline01-Deploy-AlloyDB  # Exact name in Azure DevOps
    trigger: none  # We'll trigger this manually
    
  # Pipeline 2 - Cloud Run Deployment  
  - pipeline: cloudrun-pipeline
    source: Pipeline02-Deploy-CloudRun  # Exact name in Azure DevOps
    trigger: none  # We'll trigger this manually

variables:
  - group: 'shared-variables'
  - name: TARGET_REGION
    value: 'europe-west3'

stages:
# Stage 1: Trigger AlloyDB Pipeline
- stage: TriggerAlloyDB
  displayName: 'Trigger AlloyDB Deployment Pipeline'
  jobs:
  - job: TriggerPipeline01
    displayName: 'Start AlloyDB Pipeline'
    steps:
    - task: TriggerPipeline@1
      displayName: 'Trigger Pipeline01 - Deploy AlloyDB'
      inputs:
        serviceConnection: 'azure-devops-service-connection'
        project: '$(System.TeamProject)'
        Pipeline: 'Pipeline01-Deploy-AlloyDB'
        waitForCompletion: true
        pipelineParameters: |
          region: $(TARGET_REGION)
          environment: dr
    
    - task: PowerShell@2
      displayName: 'Verify AlloyDB Pipeline Completion'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "AlloyDB Pipeline completed successfully"
          Write-Host "Pipeline Status: $(agent.jobstatus)"

# Stage 2: Trigger Cloud Run Pipeline (only if Stage 1 succeeds)
- stage: TriggerCloudRun
  displayName: 'Trigger Cloud Run Deployment Pipeline'
  dependsOn: TriggerAlloyDB
  condition: succeeded()
  jobs:
  - job: TriggerPipeline02
    displayName: 'Start Cloud Run Pipeline'
    steps:
    - task: TriggerPipeline@1
      displayName: 'Trigger Pipeline02 - Deploy Cloud Run'
      inputs:
        serviceConnection: 'azure-devops-service-connection'
        project: '$(System.TeamProject)'
        Pipeline: 'Pipeline02-Deploy-CloudRun'
        waitForCompletion: true
        pipelineParameters: |
          region: $(TARGET_REGION)
          environment: dr
          alloydb_endpoint: $(AlloyDB.Endpoint)  # Pass output from previous pipeline
    
    - task: PowerShell@2
      displayName: 'Verify Cloud Run Pipeline Completion'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Cloud Run Pipeline completed successfully"
          Write-Host "Both pipelines executed in sequence!"

# Stage 3: Final Validation
- stage: FinalValidation
  displayName: 'Post-Deployment Validation'
  dependsOn: TriggerCloudRun
  condition: succeeded()
  jobs:
  - job: ValidateDeployment
    displayName: 'Validate Complete Deployment'
    steps:
    - task: PowerShell@2
      displayName: 'Run Integration Tests'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Running integration tests..."
          # Add your validation logic here
          Write-Host "✅ All pipelines completed successfully!"
